### ISSUE TITLE
Symantec Endpoint Protection

### ISSUE THREAD

**Issue by DragonWraith** [AMXAUNZ/Magic-DXLink-Configurator#55]
Just installed latest version of Magic DXLink Configurator, and the Symantec virus software deployed throughout our company removes the Magic_DXLink_Configurator.exe file as it detects it as a Trojan Virus. Did not have a problem with earlier versions of program (3.2.3).

**Comment by jmagic** [comment]
Hello,

Unfortunately, I don't have the ability to sign my code, which means it is sometimes picked up by antivirus software. 

Most people have this issue when the auto update downloads the file for them. You can try downloading it manually from here: https://github.com/AMXAUNZ/Magic-DXLink-Configurator/releases

If you would like to help out, please report this as a false positive to Symantec here:
 https://submit.symantec.com/false_positive/ 
Maybe they will stop detecting it then...

Worst case, you can continue to use v3.2.3.

I'm sorry I don't have any better recommendations, unfortunately, there are no changes I can make to the code to stop this from happening. 

Thanks for letting me know,
Jim M
