### ISSUE TITLE
MSE Baseline feature gone in 4.0.1?

### ISSUE THREAD

**Issue by jsb5151** [AMXAUNZ/Magic-DXLink-Configurator#57]
I can't find the MSE Baseline option in the 4.0.1 version of the Configurator; was this intentionally dropped?

**Comment by jmagic** [comment]
Hi jsb5151,

I guess I forgot to put it back in the new version. I'm working on it now and should have a new release shortly. 


Thanks,
Jim M

**Comment by jmagic** [comment]
Hi jsb5151,
MSE Baseline is back:
https://github.com/avt-its-simple/Magic-DXLink-Configurator/releases/tag/v4.0.2

Enjoy!
Jim
